### PR TITLE
feat: Lock Status Method (APPROVED - ON HOLD FOR RELEASE DATE)

### PR DESCRIPTION
**Pull request by JacobAndrewSmith92**
The goal of this ticket is to add the new security endpoint and lock_status method to the ruby-sdk.

- Added mapping for `/security` to `lock_status` when using a batch request.

Asana: https://app.asana.com/0/1205281929337658/1205139255747902/f

### CODE REVIEW

**Review by wikiadrian — COMMENTED** [review]
Could we add docs for the lock status 

https://github.com/smartcar/ruby-sdk/blob/master/lib/smartcar/vehicle.rb#L159

API reference link: https://smartcar.com/docs/api#get-security

**Comment by JacobAndrewSmith92** [comment]
> Could we add docs for the lock status
> 
> https://github.com/smartcar/ruby-sdk/blob/master/lib/smartcar/vehicle.rb#L159
> 
> API reference link: https://smartcar.com/docs/api#get-security

Docs have been added for `lock_status`.

**Review by wikiadrian — APPROVED** [review]
LGTM!.

My checklist is:
- lock_status in the normal method
- batch enable
- lock_status in the batch method 
- docs
- inside lockstatus -> doors, windows, storage, sunroof (singular), chargingPort (singular), age

**Comment by wikiadrian** [comment]
The build doesn't pass due to two lines are longer that expected 

lib/smartcar/vehicle.rb:183:121: C: Layout/LineLength: Line is too long. [144/120]
    # Returns the lock status for a vehicle and the open status of its doors, windows, storage units, sunroof and charging port where available.
                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
lib/smartcar/vehicle.rb:184:121: C: Layout/LineLength: Line is too long. [157/120]
    # The open status array(s) will be empty if a vehicle has partial support. The request will error if lock status can not be retrieved from the vehicle or

**Pull request merged**
